[package]
name = "bevy-input-sequence"
version = "0.2.0"
edition = "2021"
authors = ["elm"]
keywords = [
    "game",
    "gamedev",
    "bevy",
    "input-sequence",
    "hotkey",
    "cheat-code",
    "key-sequence"
]
categories = [
    "game-engines",
]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/elm-register/bevy-input-sequence"
description = "Recognizes input sequences and send events"


[[example]]
name = "keycode"
path = "examples/keycode.rs"


[[example]]
name = "gamepad_button"
path = "examples/gamepad_button.rs"


[[example]]
name = "multiple_input"
path = "examples/multiple_input.rs"


[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [] }
trie-rs = { git = "https://github.com/sudarshan-reddy/kv-trie-rs.git", branch = "sudarshan-reddy/split-label-to-kv" }
bitflags = "2.4.2"
bevy-input-sequence-macro = { version = "0.1.0", path = "macro" }

[dev-dependencies]
bevy = "0.12.1"
trybuild = "1.0"
