name: Unit Test
run-name: ${{ github.actor }} is testing
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Clippy
        run: cargo clippy --tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test